# Generated by Django 4.2.27 on 2025-12-03 15:27

import apps.receipts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(default=apps.receipts.models.generate_receipt_number, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('washing', 'Washing'), ('drying', 'Drying'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('drop_off_date', models.DateTimeField(auto_now_add=True)),
                ('expected_pickup_date', models.DateTimeField()),
                ('actual_pickup_date', models.DateTimeField(blank=True, null=True)),
                ('items_description', models.TextField(help_text='Description of items')),
                ('items_count', models.IntegerField(default=0, help_text='Number of items')),
                ('special_instructions', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
