# Generated by Django 4.2.27 on 2025-12-03 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0001_initial'),
        ('laundromats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='laundromat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='laundromats.laundromat'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='receipts_receipt_0f1a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status'], name='receipts_status_7da223_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['customer'], name='receipts_custome_1c12af_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['laundromat'], name='receipts_laundro_4a84d9_idx'),
        ),
    ]
