# Generated by Django 4.2.27 on 2025-12-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'role'], name='users_active_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['laundromat', 'is_active'], name='users_laundromat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_at_idx'),
        ),
    ]
