# Generated by Django 4.2.27 on 2025-12-03 15:27

import apps.videos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('intake', 'Intake Video'), ('completion', 'Completion Video')], max_length=20)),
                ('video_file', models.FileField(help_text='Video file (max 50MB)', upload_to='videos/%Y/%m/%d/', validators=[apps.videos.models.validate_video_file_extension])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='receipts.receipt')),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['receipt', 'video_type'], name='videos_receipt_655917_idx')],
                'unique_together': {('receipt', 'video_type')},
            },
        ),
    ]
