# Generated by Django 4.2.27 on 2025-12-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='video',
            name='videos_receipt_655917_idx',
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['receipt'], name='videos_receipt_f532e4_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['receipt', 'uploaded_at'], name='videos_receipt_b4e9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['video_type'], name='videos_video_t_74bbff_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['uploaded_at'], name='videos_uploade_e91d38_idx'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('receipt', 'video_type'), name='unique_receipt_video_type'),
        ),
    ]
