# Generated by Django 4.2.27 on 2025-12-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundromats', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='laundromat',
            index=models.Index(fields=['name'], name='laundromats_name_b17e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='laundromat',
            index=models.Index(fields=['is_active'], name='laundromats_is_acti_03286e_idx'),
        ),
        migrations.AddIndex(
            model_name='laundromat',
            index=models.Index(fields=['created_at'], name='laundromats_created_cfdcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='laundromat',
            index=models.Index(fields=['updated_at'], name='laundromats_updated_400403_idx'),
        ),
    ]
